/**
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

/**
 * Creates a instance of HttpResponse.
 *
 * @constructor
 */
angular.module('TesterLib')
    .factory('HttpResponse',
        function () {
            return function HttpResponse() {
                this.statusCode = null;
                this.body = null;
                this.headers = null;
            }
        }
    );

}(angular));
