/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of AdvocateForm
 *
 * @constructor
 */
angular.module('GeniusReferralsLib')
    .factory('AdvocateForm', ['BaseModel', 'Advocate',
        function (BaseModel, Advocate) {
            var AdvocateForm = function (obj) {
                if (!obj) {
                    this.advocate = null;
                } else {
                    this.advocate = new Advocate(obj.advocate);
                }
            }
    
            AdvocateForm.prototype = new BaseModel();
            AdvocateForm.prototype.constructor = AdvocateForm;
        
            /**
             * The advocate's wrapper
             *
             * @return {Advocate}
             */
            AdvocateForm.prototype.getAdvocate = function () {
                return this.advocate;
            };
        
            /**
             * Setter for Advocate
             * 
             * @param {Advocate} value 
             */
            AdvocateForm.prototype.setAdvocate = function (value) {
                this.advocate = value;
            };
        
            return AdvocateForm;
        }
    ]);

}(angular));
