/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of BaseModel
 *
 * @constructor
 */
angular.module('GeniusReferralsLib')
    .factory('BaseModel', function () {
        var BaseModel = function () {
            // Maintain a name mapping dictionary
            this._variableDict = [];

            this.toJSON = function () {
                var newDict = {};

                for (var prop in this) {
                    if(typeof this[prop] !== "function" && prop !== "_variableDict") {
                        if (prop in this._variableDict) {
                            var value = this._variableDict[prop];
                            newDict[value] = this[prop];
                        } else {
                            newDict[prop] = this[prop];
                        }
                    }
                }

                return newDict;
            }
        }

        return BaseModel;
    });

}(angular));
