/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of BonusesForm
 *
 * @constructor
 */
angular.module('GeniusReferralsLib')
    .factory('BonusesForm', ['BaseModel', 'Bonuses',
        function (BaseModel, Bonuses) {
            var BonusesForm = function (obj) {
                if (!obj) {
                    this.bonus = null;
                } else {
                    this.bonus = new Bonuses(obj.bonus);
                }
            }
    
            BonusesForm.prototype = new BaseModel();
            BonusesForm.prototype.constructor = BonusesForm;
        
            /**
             * The bonuses' wrapper
             *
             * @return {Bonuses}
             */
            BonusesForm.prototype.getBonus = function () {
                return this.bonus;
            };
        
            /**
             * Setter for Bonus
             * 
             * @param {Bonuses} value 
             */
            BonusesForm.prototype.setBonus = function (value) {
                this.bonus = value;
            };
        
            return BonusesForm;
        }
    ]);

}(angular));
