/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ForceBonuses
 *
 * @constructor
 */
angular.module('GeniusReferralsLib')
    .factory('ForceBonuses', ['BaseModel',
        function (BaseModel) {
            var ForceBonuses = function (obj) {
                if (!obj) {
                    this.advocateToken = null;
                    this.reference = null;
                    this.bonusAmount = null;
        
                    // Append to variable dictionary
                    this._variableDict['advocateToken'] = 'advocate_token';
                    this._variableDict['bonusAmount'] = 'bonus_amount';
                } else {
                    this.advocateToken = obj.advocate_token;
                    this.reference = obj.reference;
                    this.bonusAmount = obj.bonus_amount;
            
                    // Append to variable dictionary
                    this._variableDict['advocateToken'] = 'advocate_token';
                    this._variableDict['bonusAmount'] = 'bonus_amount';
                }
            }
    
            ForceBonuses.prototype = new BaseModel();
            ForceBonuses.prototype.constructor = ForceBonuses;
        
            /**
             * The referral's token.
             *
             * @return {string}
             */
            ForceBonuses.prototype.getAdvocateToken = function () {
                return this.advocateToken;
            };
        
            /**
             * Setter for AdvocateToken
             * 
             * @param {string} value 
             */
            ForceBonuses.prototype.setAdvocateToken = function (value) {
                this.advocateToken = value;
            };
        
            /**
             * The reference number for this request. Usually the order_id, payment_id, or timestamp.
             *
             * @return {string}
             */
            ForceBonuses.prototype.getReference = function () {
                return this.reference;
            };
        
            /**
             * Setter for Reference
             * 
             * @param {string} value 
             */
            ForceBonuses.prototype.setReference = function (value) {
                this.reference = value;
            };
        
            /**
             * The bonus amount to give to the advocate.
             *
             * @return {int}
             */
            ForceBonuses.prototype.getBonusAmount = function () {
                return this.bonusAmount;
            };
        
            /**
             * Setter for BonusAmount
             * 
             * @param {int} value 
             */
            ForceBonuses.prototype.setBonusAmount = function (value) {
                this.bonusAmount = value;
            };
        
            return ForceBonuses;
        }
    ]);

}(angular));
