/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ForceBonusesForm
 *
 * @constructor
 */
angular.module('GeniusReferralsLib')
    .factory('ForceBonusesForm', ['BaseModel', 'ForceBonuses',
        function (BaseModel, ForceBonuses) {
            var ForceBonusesForm = function (obj) {
                if (!obj) {
                    this.bonus = null;
                } else {
                    this.bonus = new ForceBonuses(obj.bonus);
                }
            }
    
            ForceBonusesForm.prototype = new BaseModel();
            ForceBonusesForm.prototype.constructor = ForceBonusesForm;
        
            /**
             * The bonuses' wrapper
             *
             * @return {ForceBonuses}
             */
            ForceBonusesForm.prototype.getBonus = function () {
                return this.bonus;
            };
        
            /**
             * Setter for Bonus
             * 
             * @param {ForceBonuses} value 
             */
            ForceBonusesForm.prototype.setBonus = function (value) {
                this.bonus = value;
            };
        
            return ForceBonusesForm;
        }
    ]);

}(angular));
