/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of PaymentMethod
 *
 * @constructor
 */
angular.module('GeniusReferralsLib')
    .factory('PaymentMethod', ['BaseModel',
        function (BaseModel) {
            var PaymentMethod = function (obj) {
                if (!obj) {
                    this.username = null;
                    this.description = null;
                    this.isActive = null;
        
                    // Append to variable dictionary
                    this._variableDict['isActive'] = 'is_active';
                } else {
                    this.username = obj.username;
                    this.description = obj.description;
                    this.isActive = obj.is_active;
            
                    // Append to variable dictionary
                    this._variableDict['isActive'] = 'is_active';
                }
            }
    
            PaymentMethod.prototype = new BaseModel();
            PaymentMethod.prototype.constructor = PaymentMethod;
        
            /**
             * The username
             *
             * @return {string}
             */
            PaymentMethod.prototype.getUsername = function () {
                return this.username;
            };
        
            /**
             * Setter for Username
             * 
             * @param {string} value 
             */
            PaymentMethod.prototype.setUsername = function (value) {
                this.username = value;
            };
        
            /**
             * The description
             *
             * @return {string}
             */
            PaymentMethod.prototype.getDescription = function () {
                return this.description;
            };
        
            /**
             * Setter for Description
             * 
             * @param {string} value 
             */
            PaymentMethod.prototype.setDescription = function (value) {
                this.description = value;
            };
        
            /**
             * Is the payment method active? (true, false)
             *
             * @return {binary}
             */
            PaymentMethod.prototype.getIsActive = function () {
                return this.isActive;
            };
        
            /**
             * Setter for IsActive
             * 
             * @param {binary} value 
             */
            PaymentMethod.prototype.setIsActive = function (value) {
                this.isActive = value;
            };
        
            return PaymentMethod;
        }
    ]);

}(angular));
