/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

angular.module('GeniusReferralsLib', [])
    .factory('Configuration', [function() {
        return {
            //The base Uri for API calls
            BASEURI : "https://api.geniusreferrals.com",

            //The content type
            contentType : "application/json",

            //Your API Token, you can get your token here https://www.geniusreferrals.com/en/settings/api-access
            xAuthToken : "3b9d11374b602fb47b987dff90f1c5940a1f377f"

        };
    }
]);

}(angular));
